Allows to set a custom health check path
apollographql/router pull request #1164
Opened 2022-05-26 15:37 UTC by jcaromiq

With this change, we can customize the health check path, 
By default is working as now, with the /.well-known/apollo/server-health

2022-05-27 13:00 UTC, bnjjj requested changes
Thanks for your contribution, it looks good overall. Just a small suggestion

2022-05-27 13:00 UTC, bnjjj commented on docs/source/configuration/health-checks.mdx
> +```yml
```suggestion
```yaml title="router.yaml"
```
Our unit tests detect this to automatically test our examples in documentation

2022-05-27 13:01 UTC, bnjjj commented
Could you also add a changelog entry in `NEXT_CHANGELOG.md` please ?

2022-06-01 07:55 UTC, bnjjj commented
@jcaromiq did you sign the CLA ? I'm just wondering if the bot didn't already update the status or if you didn't already signed the CLA.

2022-06-01 08:22 UTC, jcaromiq commented
> @jcaromiq did you sign the CLA ? I'm just wondering if the bot didn't already update the status or if you didn't already signed the CLA.

Hello @bnjjj, yes I signed the CLA 2 days ago with my github account

2022-06-01 08:55 UTC, bnjjj commented
Hmm weird, could you try to `git commit --amend` and force push to try to retrigger the CLA bot ? I'm sorry for this.

2022-06-01 12:32 UTC, bnjjj approved these changes

2022-06-02 07:54 UTC, Geal approved these changes

2022-06-02 08:21 UTC, bnjjj commented on NEXT_CHANGELOG.md
> +```
```suggestion
```

By [@jcaromiq](https://github.com/jcaromiq) in https://github.com/apollographql/router/pull/1164
```

2022-06-02 08:35 UTC, merged