feat: update serialization format
apollographql/router pull request #1391
Opened 2022-07-12 18:57 UTC by me-diru

- fixes #1166
- changes data structure to a HashMap<String, String>
- updated test case
- this will not handle duplicate key values

Signed-off-by: Rohit Dandamudi <rohitdandamudi.1100@gmail.com>

2022-07-12 18:57 UTC, apollo-cla commented
@me-diru: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2022-07-12 19:04 UTC, me-diru commented
@bnjjj I am not sure about this, the `HashMap<String, String>` type doesn't allow duplicate key entries(which is what we want I think?), and also it doesn't maintain any order which leads to failing tests when I tried. 

I didn't update CHANGELOG yet ( I think we should update the NEXT_CHANGELOG though?).

let me know your thoughts, thanks!

2022-07-25 10:30 UTC, bnjjj commented
SOrry for the delay @me-diru I was on vacation. I checked the JavaScript implementation to know more about the GRPC metadata and discover that https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/metadata.ts#L25. So I think the format we want is `HashMap<String, Vec<String>>` and we don't care about ordering. You should change the type [here](https://github.com/apollographql/router/blob/cf422d04aeff604732eacab8494207673eae4e06/apollo-router/src/plugins/telemetry/otlp.rs#L206) and [here](https://github.com/apollographql/router/blob/cf422d04aeff604732eacab8494207673eae4e06/apollo-router/src/plugins/telemetry/otlp.rs#L224). Does it help you ?

2022-07-28 18:31 UTC, me-diru commented
Thanks for the response @bnjjj, I tried to follow that approach. Let me know your thoughts, thanks!

2022-07-28 18:56 UTC, me-diru commented
It still doesn't get the order of keys right, resulting in failing tests. Hashmap doesn't store data in any order, there's no static case to check. 

Avoiding Vector comes at a cost of not maintaining the order of key storage.

2022-07-29 07:19 UTC, bnjjj requested changes
Great job, 2 last bits and I think we're good. Please ensure to properly fill the `NEXT_CHANGELOG.md` file with your changes

2022-07-29 07:19 UTC, bnjjj commented on apollo-router/src/plugins/telemetry/otlp.rs
> +            map.append(key, last_value.parse().unwrap());
Do not take only the last value but append all values

2022-07-29 07:19 UTC, bnjjj commented on apollo-router/src/plugins/telemetry/snapshots/apollo_router__plugins__telemetry__otlp__metadata_map_serde__tests__serialize_metadata_map.snap
> +foo:
If you want to keep ordering to not break the test then use `IndexMap` from https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html it should already exist in our deps

2022-08-01 08:13 UTC, bnjjj approved these changes

2022-08-01 08:13 UTC, merged

2022-08-01 08:14 UTC, bnjjj commented
Great job @me-diru thanks for your contribution !