reload the configuration when receiving the SIGHUP signal
apollographql/router pull request #2015
Opened 2022-10-27 13:08 UTC by Geal

Fix #35 

This adds support for reloading configuration when receiving the SIGHUP signal. This only works on unix-like platforms, and only with the configuration file

2022-10-27 13:12 UTC, bnjjj approved these changes

2022-10-27 13:21 UTC, garypen requested changes
Looks good. One small NIT.

2022-10-27 13:21 UTC, garypen commented on apollo-router/src/router.rs
> +                                .expect("Failed to install SIGTERM signal handler");
```suggestion
                                .expect("Failed to install SIGHUP signal handler");
```

2022-10-27 14:17 UTC, garypen approved these changes

2022-10-28 08:14 UTC, Geal commented
so I suspect SIGHUP is used by the CI to stop tests so they fail :sweat_smile:

2022-11-02 13:41 UTC, merged