fix: specify content type to application/json when it throws an invalid graphql request error
apollographql/router pull request #2321
Opened 2022-12-26 16:22 UTC by bnjjj

close #2320

2022-12-29 09:31 UTC, abernix requested changes
This looks great, but needs a test before we land it — both for the `INVALID_GRAPHQL_REQUEST` response itself (of which there is currently none) and for the presence of the `content-type: application/json` header being present in that response.

2022-12-29 09:31 UTC, abernix commented on NEXT_CHANGELOG.md
> +When throwing a `INVALID_GRAPHQL_REQUEST` error, it nows specify the right content-type header.
```suggestion
When throwing a `INVALID_GRAPHQL_REQUEST` error, it nows specify the right `content-type` header.
```

2022-12-29 09:59 UTC, bnjjj commented
test added @abernix

2022-12-29 10:00 UTC, abernix approved these changes
nice!

2023-01-03 09:11 UTC, o0Ignition0o approved these changes

2023-01-03 09:38 UTC, Geal commented on NEXT_CHANGELOG.md
> +When throwing a `INVALID_GRAPHQL_REQUEST` error, it nows specify the right `content-type` header.
```suggestion
When throwing a `INVALID_GRAPHQL_REQUEST` error, it now specifies the right `content-type` header.
```

2023-01-03 09:40 UTC, Geal approved these changes

2023-01-04 10:39 UTC, merged