Add tests for per-type metrics
apollographql/router pull request #2701
Opened 2023-02-28 16:44 UTC by SimonSapin

In order to test latency historgram computation and add synthetic field errors, this new test does not make network requests to subgraphs but instead mocks their responses.

Fixes https://github.com/apollographql/router/issues/2592

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

2023-02-28 16:45 UTC, SimonSapin commented
This PR is a draft because:

* At this point it is more of a proof-of-concept of the kind of test we can write than a definitive answer to https://github.com/apollographql/router/issues/2592
* It should be rebased once https://github.com/apollographql/router/pull/2700 is merged

2023-03-07 04:36 UTC, bonnici commented
I was actually able to use our new (unmerged) [integration test framework](https://github.com/mdg-private/monorepo/pull/11650) to test these sample reports and I noticed a few issues. 

I first ingested a sample gateway report containing errors I had stored from somewhere (i'll put the JSON later in the comment). The results are [here](https://studio-staging.apollographql.com/graph/z-end-to-end-ingestion-integration-test/operations?range=lastMonth&tab=errors&variant=test-ingest-1678161965305). The error stats look good based on what's in the report - 3 requests, 3 errors, all with the path "service:accounts.me".

Then I copied the snapshot data, translated it to JSON, and used that in place of the statsWithContext in that same report. The results are [here](https://studio-staging.apollographql.com/graph/z-end-to-end-ingestion-integration-test/operations?range=lastMonth&tab=errors&variant=test-ingest-1678162063366). There are some errored paths, but no errored requests, and also no operation executions found. 

I made some changes to the report and the results looked better. I added a latency_count array (instead of using the string `"[latency_count]"`), and updated "requests_with_errors_count" (the child of "query_latency_stats") to be 1. I'm not sure why the string `"[latency_count]"` is in the snapshot (maybe that's just an issue with how the snapshot works), but when reporting errors, you need to specify the error count both in the "query_latency_stats" as well as "root_error_stats". The "root_error_stats" data is used for path-related errors and the error counts in "query_latency_stats" is used as the top level "how many errors did this query encounter" number. It's not ideal but that's how it all seems to work at the moment.

The updated results are [here](https://studio-staging.apollographql.com/graph/z-end-to-end-ingestion-integration-test/operations?range=lastMonth&tab=errors&variant=test-ingest-1678163417517). You can see that there are errors reported in the errors tab with the right paths and counts, and the query tab has some reported operations.

For reference, here is the JSON for the sample report I have from Apollo Server:
```
{
  "header": {
    "hostname": "nickmarsh-mbp",
    "agentVersion": "apollo-server-core@3.9.0",
    "runtimeVersion": "node v16.17.0",
    "uname": "darwin, Darwin, 21.5.0, arm64)",
    "executableSchemaId": "fb1579ee284bd59fd2e7facadd989f8cd54e912c52e783b982269d63d5f5a98f",
    "graphRef": "Odyssey-Voyage-2-3jm8nf@current"
  },
  "endTime": {
    "seconds": "1661468250",
    "nanos": 456000000
  },
  "tracesPerQuery": {
    "# MonolightQueryError\nquery MonolightQueryError{featuredListings{bookings{guest{id name}id}id title}me{id name}}": {
      "statsWithContext": [
        {
          "context": {
            "clientName": "",
            "clientVersion": ""
          },
          "queryLatencyStats": {
            "requestCount": "3",
            "cacheHits": "0",
            "persistedQueryHits": "0",
            "persistedQueryMisses": "0",
            "rootErrorStats": {
              "children": {
                "service:accounts": {
                  "children": {
                    "me": {
                      "errorsCount": "3",
                      "requestsWithErrorsCount": "3"
                    }
                  },
                  "errorsCount": "0",
                  "requestsWithErrorsCount": "0"
                }
              },
              "errorsCount": "0",
              "requestsWithErrorsCount": "0"
            },
            "requestsWithErrorsCount": "3",
            "registeredOperationCount": "0",
            "forbiddenOperationCount": "0",
            "latencyCount": [
              "-107",
              "1",
              "-2",
              "2"
            ],
            "requestsWithoutFieldInstrumentation": "0"
          },
          "perTypeStat": {
            "Query": {
              "perFieldStat": {
                "featuredListings": {
                  "returnType": "[Listing!]!",
                  "errorsCount": "0",
                  "observedExecutionCount": "3",
                  "requestsWithErrorsCount": "0",
                  "latencyCount": [
                    "-86",
                    "1",
                    "0",
                    "2"
                  ],
                  "estimatedExecutionCount": "3"
                },
                "_entities": {
                  "returnType": "[_Entity]!",
                  "errorsCount": "0",
                  "observedExecutionCount": "3",
                  "requestsWithErrorsCount": "0",
                  "latencyCount": [
                    "-91",
                    "1",
                    "-4",
                    "1",
                    "-3",
                    "1"
                  ],
                  "estimatedExecutionCount": "3"
                },
                "me": {
                  "returnType": "User!",
                  "errorsCount": "3",
                  "observedExecutionCount": "3",
                  "requestsWithErrorsCount": "3",
                  "latencyCount": [
                    "-42",
                    "1",
                    "1",
                    "-12",
                    "1"
                  ],
                  "estimatedExecutionCount": "3"
                }
              }
            },
            "Listing": {
              "perFieldStat": {
                "id": {
                  "returnType": "ID!",
                  "errorsCount": "0",
                  "observedExecutionCount": "9",
                  "requestsWithErrorsCount": "0",
                  "latencyCount": [
                    "-12",
                    "2",
                    "0",
                    "1",
                    "1",
                    "-2",
                    "1",
                    "-2",
                    "1",
                    "-3",
                    "1",
                    "0",
                    "1",
                    "1"
                  ],
                  "estimatedExecutionCount": "9"
                },
                "title": {
                  "returnType": "String!",
                  "errorsCount": "0",
                  "observedExecutionCount": "9",
                  "requestsWithErrorsCount": "0",
                  "latencyCount": [
                    "-9",
                    "2",
                    "1",
                    "0",
                    "1",
                    "1",
                    "0",
                    "1",
                    "1",
                    "-3",
                    "1",
                    "1"
                  ],
                  "estimatedExecutionCount": "9"
                },
                "bookings": {
                  "returnType": "[Booking]!",
                  "errorsCount": "0",
                  "observedExecutionCount": "9",
                  "requestsWithErrorsCount": "0",
                  "latencyCount": [
                    "-75",
                    "1",
                    "0",
                    "1",
                    "2",
                    "1",
                    "2",
                    "0",
                    "2"
                  ],
                  "estimatedExecutionCount": "9"
                }
              }
            },
            "Booking": {
              "perFieldStat": {
                "id": {
                  "returnType": "ID!",
                  "errorsCount": "0",
                  "observedExecutionCount": "36",
                  "requestsWithErrorsCount": "0",
                  "latencyCount": [
                    "-8",
                    "14",
                    "11",
                    "3",
                    "0",
                    "1",
                    "1",
                    "1",
                    "1",
                    "-6",
                    "1",
                    "2",
                    "-2",
                    "1"
    [...]

2023-03-07 17:06 UTC, SimonSapin commented
(I took the liberty to edit your comment with `<details>…</details>` for readability.)

`[latency_count]` is the snapshot-testing crate `insta` redacting some of the data, in this case because it’s based on actual clocks and could change from one run to the next.

> when reporting errors, you need to specify the error count both in the "query_latency_stats" as well as "root_error_stats". The "root_error_stats" data is used for path-related errors and the error counts in "query_latency_stats" is used as the top level "how many errors did this query encounter" number. It's not ideal but that's how it all seems to work at the moment.

Do you mean both `QueryLatencyStats::requests_with_errors_count` and `QueryLatencyStats::root_error_stats`? Yes I think the Router’s treatment of them is inconsistent at the moment. We build `root_error_stats` based on FTV1 from subgraphs, and since it’s per-path it only concerns [field errors](https://spec.graphql.org/October2021/#sec-Errors.Field-errors) (as opposed to request errors). It ignores field errors generated by the Router itself (and probably shouldn’t?) `requests_with_errors_count` is based on what HTTP status code the Router is about to respond. The test in this PR artificially adds field errors in mocked FTV1 data but doesn’t change the status code.

2023-03-08 00:03 UTC, bonnici commented
TIL about `<details>`! Thanks for that.

Regarding error reporting - this is another thing where maybe Router is doing something different to Server, and maybe that's ok, but it does make things look a bit "weird" in Studio. As in, if you go to the Operations page, it shows up with the message "1 operations failed while executing path service:accounts._entities.name", but then we don't actually show as any errors occurring with the operation as a whole since the `QueryLatencyStats::requests_with_errors_count` field is 0. I don't really have enough context around GraphQL errors as a whole to be able to say what we "should" do though, perhaps @glasser can chime in on that a bit?

2023-03-08 00:16 UTC, glasser commented
Agree with Nick. When a single query_latency_stats has a root_error_stats tree showing nonzero requests_with_errors_count but its top-level requests_with_errors_count is 0, something is wrong.

2023-03-09 11:07 UTC, SimonSapin commented
Right, broken mocked subgraph responses (with errors in FTV1 but not in GraphQL `errors`) caused a broken metrics report. I’ve pushed another commit to fix that

2023-03-13 03:35 UTC, bonnici commented
The report side of this looks good to me but I'll leave the approval to someone who can review the rust side.

2023-03-20 14:23 UTC, SimonSapin commented
Alright, let’s get this merged. We can always add more tests of this kind in other PRs

2023-03-20 14:41 UTC, BrynCooke approved these changes
Looks great.
Suggestion to use wiremock, but you'll have to decide if it's worth it.

2023-03-20 14:44 UTC, BrynCooke requested changes
Looks great.
Suggestion to use wiremock, but you'll have to decide if it's worth it.

2023-03-20 14:44 UTC, BrynCooke commented on apollo-router/tests/apollo_reports.rs
> +            std::env::set_var("APOLLO_KEY", "test");
I'm not sure about setting these env variables. Some other tests may rely on these values being valid.

2023-03-20 16:24 UTC, BrynCooke approved these changes

2023-03-21 10:53 UTC, Geal approved these changes

2023-03-23 09:23 UTC, SimonSapin commented
Yes, both the env variable and the custom Axum server to receive reports are pre-existing

2023-03-23 09:24 UTC, merged