helm chart: allow specifying extra containers
apollographql/router pull request #2881
Opened 2023-03-30 16:37 UTC by pcarrier

Allow sidecars, like coprocessors, in the official helm chart.

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

2023-03-31 07:20 UTC, garypen requested changes
Thanks! I think this is a great addition. In addition to my `helm-docs` suggestion, could you also please fill in a [changeset description](https://github.com/apollographql/router/blob/dev/.changesets/README.md) for your PR.

2023-03-31 07:20 UTC, garypen commented on helm/chart/router/values.yaml
> +# An array of extra containers
We use [helm-docs](https://github.com/norwoodj/helm-docs) to generate https://github.com/apollographql/router/tree/dev/helm/chart/router#readme. It takes comments in this format:

```
# -- Set to existing PriorityClass name to control pod preemption by the scheduler
```
to populate the **Description** field in the table. I really should put a comment about this at the top of the values.yaml file at some point...

Anyway: NIT:
```suggestion
# -- An array of extra containers to include in the router pod
```

2023-04-04 06:55 UTC, o0Ignition0o approved these changes

2023-04-04 07:56 UTC, garypen approved these changes

2023-04-04 08:41 UTC, merged