add a metric tracking query planning time
apollographql/router pull request #2974
Opened 2023-04-19 08:15 UTC by Geal

we need a way to track query planning time without going through the traces

2023-04-20 09:09 UTC, bnjjj requested changes
Could you add it in documentation too please ?

2023-05-03 09:41 UTC, Geal commented
> Could you add it in documentation too please ?
fixed in [ef20655](https://github.com/apollographql/router/pull/2974/commits/ef20655c7d87c1259d599babc5fa72d1aab49656)

2023-05-03 16:02 UTC, bnjjj approved these changes

2023-05-04 14:02 UTC, merged

2023-05-05 11:46 UTC, abernix commented
I'd also suggest putting both the metric name and perhaps a link to the docs in the changelog for the future. 😄