Geal/parent based sampling test
apollographql/router pull request #3136
Opened 2023-05-24 06:40 UTC by Geal

*Description here*

Fixes #issue_number

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

2023-05-24 10:40 UTC, BrynCooke requested changes
We need to add a tests for sampling. This should have a 50% rate and verify in jaeger that no half traces exist. 
Separate tests are needed for local and remote roots.

2023-05-25 07:35 UTC, Geal commented
> We need to add a tests for sampling
these tests are useful in their current state and should be merged. Adding a sampling rate is likely to be more work to get it right (high potential of flaky test), that can be done as a follow up

2023-05-25 08:04 UTC, BrynCooke commented
I think it's worth the effort if we want to try the prefiltering thing again. I would be OK with merging as long as any prefiltering follow up does include these tests.

Here's the reason:

If no layer registers interest in a span event, tracing registry will globally disable the span. This means that the span is not created at all rather than it just being prefiltered for a particular layer.
Subsequent child spans will then look like root spans and risk making the sampling decision again.

The work for this test needs to be done before any solution can be merged so unless there is a good reason to defer it I'd try and add it here for the same reason that these tests have been split out from the original PR that these came from.

2023-05-25 08:13 UTC, Geal commented
> If your proposal is that we merge this stuff, and then make another PR for the tests and then a follow up PR for any prefiltering that that is OK.

Right now I have a good idea of how I will fix prefiltering, but no idea how to make a non flaky test around random based sampling. So I will work on the prefiltering fix, but we won't merge it until we have a test for the sampling

2023-05-25 08:30 UTC, BrynCooke approved these changes

2023-05-31 10:13 UTC, Geal commented
it looks like the tests local_root, remote_root and reload never passed , looking into it

2023-05-31 10:27 UTC, Geal commented
it appears the tests are not independent. If I run them individually, they pass, but as a whole they will fail

2023-07-05 09:15 UTC, BrynCooke commented
I figured out what the issue was as part of #3364
Once this is merged this PR will need to be rebased, but then things will work.

2023-07-07 14:21 UTC, Geal commented
ok so after a rebase the tests are now failing even individually

2023-08-02 16:49 UTC, BrynCooke commented
It required more than a rebased in the end. Tests should be passing now.

2023-08-07 09:55 UTC, Geal commented
great, thanks!

2023-08-09 11:58 UTC, o0Ignition0o approved these changes

2023-08-09 11:58 UTC, o0Ignition0o commented on apollo-router/tests/jaeger_test.rs
> +    //println!("{}", serde_json::to_string_pretty(&trace)?);
```suggestion
    tracing::debug!("{}", serde_json::to_string_pretty(&trace)?);
```

2023-08-09 12:00 UTC, o0Ignition0o commented
I m not sure if any action is needed wrt [this comment](https://github.com/apollographql/router/pull/3136/files#r1282179670) and the need of percent based sampling. otherwise lgtm.

2023-08-09 12:34 UTC, merged