Improve Rhai errors
apollographql/router pull request #3254
Opened 2023-06-13 18:11 UTC by dbanty

This PR attempts to improve the Rhai error handling and debugging experience. The only tweak to the code is that if there is an error in the main script, the path to that script is included in the error. Previously, the plugin name `apollo.rhai` (which _looks_ like a file name for a script) combined with the fact that line numbers/positions are incorrect in syntax errors, made it seem like some internal generated code was failing.

This does _not_ add paths to errors in imported modules, since the module names seemed clear enough to me.

Additionally, I added a "Debugging" section to the Rhai docs—this needs some additions from folks who know Rhai better than I do, but it has some basics to get started. Specifically, I think we should add some advice on testing Rhai scripts.

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [x] Changes are compatible[^1]
- [x] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [x] Unit Tests
    - [x] Integration Tests
    - [x] Manual Tests

2023-06-15 09:10 UTC, garypen requested changes
Thanks for the contribution. This is a nice change and should make life simpler for users.

I'll re-review after you look at my suggested changes.

2023-06-15 09:10 UTC, garypen commented on apollo-router/src/plugins/rhai/mod.rs
> +use anyhow::anyhow;
Don't need `anyhow`. `BoxError` will happily box up a `String`.

2023-06-15 09:10 UTC, garypen commented on apollo-router/src/plugins/rhai/mod.rs
> +            .map_err(|err| anyhow!("in Rhai script {}: {}", main.display(), err))?;
```suggestion
            .map_err(|err| format!("in Rhai script {}: {}", main.display(), err))?;
```

2023-06-15 20:32 UTC, dbanty commented
Thanks @garypen, all set! Can't believe I didn't know you could `From<String> for Box<dyn Error>`!

2023-06-16 08:45 UTC, garypen approved these changes

2023-06-16 08:45 UTC, merged