don't reload the router if the schema/license hasn't changed
apollographql/router pull request #3478
Opened 2023-07-20 13:40 UTC by bnjjj

The router is performing frequent schema reloads due to notifications from uplink. In the majority of cases a schema reload is not required, because the schema hasn't actually changed.

We won't reload the router if the schema/license hasn't changed.

Fixes #3180

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

2023-07-20 14:34 UTC, bnjjj commented on apollo-router/src/state_machine.rs
> +                    tracing::info!("reload complete (nothing has been updated)");
Good suggestion ! I'll do this

2023-07-20 14:55 UTC, garypen approved these changes

2023-07-21 09:43 UTC, BrynCooke requested changes

2023-07-21 09:43 UTC, BrynCooke commented on apollo-router/src/state_machine.rs
> +                    );
```suggestion
                    tracing::debug!(
                        new_schema = schema_reload,
                        new_license = license_reload,
                        new_configuration = configuration_reload,
                        "no reload necessary"
                    );
```

2023-07-21 14:05 UTC, BrynCooke commented on apollo-router/src/state_machine.rs
> +                    );
How about `reload event processed` (at info level)?

2023-07-24 15:51 UTC, BrynCooke approved these changes

2023-07-25 07:42 UTC, merged