add lifecycle support to helm chart
apollographql/router pull request #3570
Opened 2023-08-14 17:14 UTC by bjoernw

In order to reduce the instances of 502s during deployments I would like to add a preStop hook with a sleep to give sending services enough time to receive DNS updates. This PR exposes the container's lifecycle object to accomplish that.

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [X] Changes are compatible[^1]
- [X] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [X] Manual Tests

**Exceptions**
- unit tests
- integration tests

Helm changes not applicable to unit/integration tests. Installed the chart into a kind cluster with and without the property. Both worked.

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

2023-08-14 17:31 UTC, pvnui approved these changes

2023-08-15 09:55 UTC, garypen requested changes
Looks good. Thanks very much for the contribution. Could you do the following:
 - revert the change to README.md (we auto-generate that when we cut a release)
 - add a changelog as described in `.changesets/README.md`

2023-08-16 07:42 UTC, garypen approved these changes

2023-08-16 07:58 UTC, garypen commented
`kubernetes 1.28.0` was released yesterday and our helm validation tooling (`kubeconform`) doesn't have support for it yet. We'll wait a while for support to be added before trying to merge this.

2023-08-16 12:26 UTC, merged