Supergraph coprocessor implementation
apollographql/router pull request #3647
Opened 2023-08-22 14:24 UTC by Geal

*Description here*

Fixes #issue_number

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

2023-08-23 08:59 UTC, o0Ignition0o commented on apollo-router/src/plugins/coprocessor/supergraph.rs
> +        .and_sdl(sdl_to_send)
🙌

2023-08-23 08:59 UTC, Geal commented on CHANGELOG.md
> +
```suggestion
```

2023-08-23 08:59 UTC, Geal commented on .changesets/feat_geal_supergraph_coprocessor2.md
> +By [@Geal](https://github.com/Geal) in https://github.com/apollographql/router/pull/3647
```suggestion
### Supergraph coprocessor implementation ([PR #3647](https://github.com/apollographql/router/pull/3647))


Coprocessors now support supergraph service interception. 

On the request side, the coprocessor payload can contain:
- method
- headers
- body
- context
- sdl

On the response side, the payload can contain:
- status_code
- headers
- body
- context
- sdl

The supergraph request body contains:
* query
* operation name
* variables
* extensions

The supergraph response body contains:
* label
* data
* errors
* extensions

When using `@defer` or subscriptions a supergraph response may contain multiple GraphQL responses, and the coprocessor will be called for each.

By [@Geal](https://github.com/Geal) in https://github.com/apollographql/router/pull/3647
```

2023-09-05 09:06 UTC, BrynCooke requested changes
Needs the metric added:
apollo.router.operations.coprocessor 

Plus update the test for apollo.router.config.coprocessor to ensure that it is doing the right thing.

2023-09-05 10:11 UTC, Geal commented
> Needs the metric added:
> apollo.router.operations.coprocessor

[cb4d33b](https://github.com/apollographql/router/pull/3647/commits/cb4d33b5e209835ad1a49b9eaa1a6d6bb0149504)

> Plus update the test for apollo.router.config.coprocessor to ensure that it is doing the right thing.

[773bd02](https://github.com/apollographql/router/pull/3647/commits/773bd026b7c9e87817ba38799214103c84020ba0)

2023-09-13 16:47 UTC, garypen approved these changes

2023-09-13 16:51 UTC, o0Ignition0o approved these changes

2023-09-14 07:46 UTC, BrynCooke approved these changes

2023-09-14 07:59 UTC, merged