Metric should not be counted as errors for metrics
apollographql/router pull request #3724
Opened 2023-09-01 15:35 UTC by BrynCooke

*Description here*

Fixes #issue_number

**Checklist**

Complete the checklist (and note appropriate exceptions) before a final PR is raised.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual Tests:
    - please document the manual testing (extensively) in the Exceptions.
    - please raise a separate issue to automate the test and label it (or ask for it to be labeled) as `manual test`

2023-09-04 13:45 UTC, bnjjj approved these changes

2023-09-05 11:24 UTC, o0Ignition0o commented on apollo-router/src/plugins/telemetry/metrics/layer.rs
> +            );
let's make all of these failfast_debug! instead of tracing::error.

2023-09-05 11:26 UTC, o0Ignition0o requested changes
https://github.com/apollographql/router/blob/8e86ef41a3b5eef7f528fc827eeb227f33c27445/apollo-router/src/lib.rs#L23 failfast_debug or failfast_error would allow us to spot attribute type issues.

2023-09-06 08:54 UTC, BrynCooke commented
@o0Ignition0o I ended up adding another macro in [cc9cb64](https://github.com/apollographql/router/pull/3724/commits/cc9cb649ec2de45823e986116e9bb72d8f2d29b0)

The behavior is that we will log at debug level and panic on debug builds.

2023-09-06 09:16 UTC, o0Ignition0o approved these changes
Looking great! 1 small nit otherwise LGTM

2023-09-06 09:16 UTC, o0Ignition0o commented on apollo-router/src/plugins/telemetry/metrics/layer.rs
> +        panic!("metric type error, see DEBUG log for details. Release builds will not panic but will still emit an debug log message");
```suggestion
        panic!("metric type error, see DEBUG log for details. Release builds will not panic but will still emit a debug log message");
```

2023-09-06 10:36 UTC, merged