exposing topologySpreadConstraints on the helm chart
apollographql/router pull request #3892
Opened 2023-09-22 22:08 UTC by bjoernw

*Description here*
This allows users to set `topologySpreadConstraints` which can be used to more evenly spread pods out over nodes/AZs/etc. and prevent uneven utilization of federation pods.

Fixes #3891

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [X] Changes are compatible[^1]
- [X] Documentation[^2] completed
- [X] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [X] Manual Tests

**Exceptions**
Tested helm chart template generation locally

*Note any exceptions here*
N/A
**Notes**
N/A

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2023-09-29 07:01 UTC, Meemaw commented
Hey @garypen any blockers to get this in? Its a relatively small change, but super useful one!

2023-09-29 08:48 UTC, garypen commented
> Hey @garypen any blockers to get this in? Its a relatively small change, but super useful one!

Two things:
 - I'm on vacation (back on Monday)
 - I was waiting to re-enable `kubeconform` (which I think may have just happened)

Expect something to happen next week.

2023-10-03 14:32 UTC, garypen requested changes
Looks good. If you don't mind making those changes we can commit this.

2023-10-03 14:32 UTC, garypen commented on helm/chart/router/values.yaml
> +#    whenUnsatisfiable: ScheduleAnyway
```suggestion
# -- Sets the [topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) for Deployment pods
topologySpreadConstraints: []
```

2023-10-04 18:57 UTC, bjoernw commented
@garypen done

2023-10-05 11:07 UTC, garypen approved these changes

2023-10-05 11:08 UTC, merged