release: v1.34.0
apollographql/router pull request #4207
Opened 2023-11-15 09:59 UTC by goto-bus-stop

> **Note**
> **This particular PR should be true-merged to `main`.**

This PR represents the merge to `main` of the v1.34.0 release.

This PR is **primarily a merge commit**, so reviewing every individual commit shown below is **not necessary** since those have been reviewed in their own PR.

**However!** Some things to review on this PR:

- Does this PR target the right branch? (usually, `main`)
- Are the appropriate **version bumps** and **release note edits** in the end of the commit list (or within the last few commits).  In other words, "Did the 'release prep' PR actually land on this branch?"

If those things look good, this PR is good to merge.

2023-11-15 10:06 UTC, goto-bus-stop commented
I think the merge conflicts are just because the 1.33.2 release was squash-merged into dev here: https://github.com/apollographql/router/pull/4112

I can resolve them here and then it should be fine in the future after the next merge of main into dev

2023-11-15 12:01 UTC, garypen approved these changes

2023-11-15 13:13 UTC, abernix reviewed
I've left a few comments on the changelog, but I would like @shorgi to take an overall look and also for @chandrikas to note/review the details of the Enterprise features.

2023-11-15 13:13 UTC, abernix commented on CHANGELOG.md
> +When importing directives through the `@link` directive, they can be renamed. This makes sure that the authorization plugin can still recognize its directives when they have been renamed.
```suggestion
When importing directives into subgraph schemas using the `@link` directive it is possible to rename the directive [using the `as:` parameter](https://specs.apollo.dev/link/v1.0/#@link.as). It is now possible to do this for authorization directives and they will be recognized appropriately even if they have been renamed.
```

2023-11-15 13:13 UTC, abernix commented on CHANGELOG.md
> +Configuration between tracing and metrics was inconsistent and did not align with otel spec terminology. The following changes have been made to router.yaml configuration:
```suggestion
Configuration between tracing and metrics was inconsistent and did not align with the terminology defined in the OpenTelemetry specification. To correct this, the following changes have been made to the router's YAML configuration:
```

2023-11-15 13:13 UTC, abernix commented on CHANGELOG.md
> +### Router should respond with subscription-protocol header for callback ([Issue #3929](https://github.com/apollographql/router/issues/3929))
```suggestion
### Router should respond with `subscription-protocol` header for callback ([Issue #3929](https://github.com/apollographql/router/issues/3929))
```

2023-11-15 13:13 UTC, abernix commented on CHANGELOG.md
> +Callback protocol documentation specifies that router responds with `subscription-protocol: callback/1.0` header to the initialization (check) message. Currently router does not set this header on th
```suggestion
The router will now include a `subscription-protocol: callback/1.0` header on the response to a initialization (check) message, per the [callback protocol documentation](https://www.apollographql.com/docs/router/executing-operations/subscription-callback-protocol).
```

@bnjjj Note that the [docs](https://www.apollographql.com/docs/router/executing-operations/subscription-callback-protocol) now differ from [the `dev-docs`](https://github.com/apollographql/router/blob/dev/dev-docs/callback_protocol.md)!   Can you fix that?

2023-11-16 12:58 UTC, abernix commented on CHANGELOG.md
> +Callback protocol documentation specifies that router responds with `subscription-protocol: callback/1.0` header to the initialization (check) message. Currently router does not set this header on th
Covered by https://github.com/apollographql/router/issues/3937 already.  Thanks!

2023-11-16 13:02 UTC, abernix commented on CHANGELOG.md
> +If none of the above are found then the service name will be set to `unknown_service:apollo_router` or `unknown_service` if the executable name cannot be determined.
Ok, I guess that's probably `router` for us then?:

```suggestion
If none of the above are found then the service name will be set to `unknown_service:router` or `unknown_service` if the executable name cannot be determined.
```

2023-11-16 13:05 UTC, BrynCooke requested changes
Default OpenTelemetry service name fixes

2023-11-16 13:05 UTC, BrynCooke commented on docs/source/configuration/metrics.mdx
> +If none of the above are found then the service name will be set to `unknown_service:apollo_router` or `unknown_service` if the executable name cannot be determined.
```suggestion
If none of the above are found then the service name will be set to `unknown_service:router` or `unknown_service` if the executable name cannot be determined.
```

2023-11-16 13:05 UTC, BrynCooke commented on docs/source/configuration/tracing.mdx
> +If none of the above are found then the service name will be set to `unknown_service:apollo_router` or `unknown_service` if the executable name cannot be determined.
```suggestion
If none of the above are found then the service name will be set to `unknown_service:router` or `unknown_service` if the executable name cannot be determined.
```

2023-11-16 13:05 UTC, BrynCooke commented on CHANGELOG.md
> +If none of the above are found then the service name will be set to `unknown_service:apollo_router` or `unknown_service` if the executable name cannot be determined.
```suggestion
If none of the above are found then the service name will be set to `unknown_service:router` or `unknown_service` if the executable name cannot be determined.
```

2023-11-16 13:13 UTC, BrynCooke approved these changes

2023-11-17 10:00 UTC, merged