update macos builds in CI to use new m1 machines
apollographql/router pull request #4484
Opened 2024-01-16 11:43 UTC by garypen

Update the build pipeline to produce apple silicon binaries for macos. Additionally, update the installer script to reflect the changes in binary architecture for mac os and try to do the right thing for binaries which are:

`<= v1.37.0` ==> intel binaries
`> v1.37.0` ==> arm64 binaries

Fixes #3902 

also see: #4483 

Note: This change *must* be part of the next release after 1.37.0 or else we need to update the changes to the installer script.

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-01-17 10:24 UTC, bnjjj approved these changes

2024-01-17 10:39 UTC, abernix requested changes

2024-01-17 10:39 UTC, abernix commented on .changesets/maint_garypen_m1_changes.md
> +### update macOS builds in CI to use new m1 machines ([Issue #3902](https://github.com/apollographql/router/issues/3902))
For this user-facing heading, I think this title should highlight the outcome/impact more than the technical implementation detail (based on title, this sounds like it is just a CI change):

```suggestion
### Pre-built binaries are only available for Apple Silicon ([Issue #3902](https://github.com/apollographql/router/issues/3902))
```

2024-01-17 10:39 UTC, abernix commented on .changesets/maint_garypen_m1_changes.md
> +We have raised an [issue](https://github.com/apollographql/router/issues/4483) that describes options for Intel based macOS users. Please let us know in that issue if the alternatives we suggest (Doc
```suggestion
We have raised [an issue](https://github.com/apollographql/router/issues/4483) that describes options for Intel based macOS users. Please let us know in that issue if the alternatives we suggest (e.g., Docker, source build) don't work for you so we can discuss alternatives.
```

2024-01-17 10:39 UTC, abernix commented on scripts/install.sh
> +        err "no precompiled binaries available on mac os for CPU architecture: $_cputype"
```suggestion
        say "No precompiled binaries available on macOS for CPU architecture: $_cputype"
        say "The most recent macOS release which supports Intel is 1.37.0"
        say "Please refer to this issue for more details:  https://github.com/apollographql/router/issues/4483"
        err "No precompiled binaries available on macOS for CPU architecture: $_cputype"
```

2024-01-17 12:15 UTC, abernix approved these changes
LGTM!

2024-01-17 12:31 UTC, merged

2024-01-18 15:13 UTC, abernix commented
For posterity: See follow-up PRs #4415 and #4418.