add tests for typed fragment application
apollographql/router pull request #470
Opened 2022-02-15 11:12 UTC by Geal

Fix #469

no fix for now, only tests showing the issue

2022-02-15 14:37 UTC, Geal commented
ok so my fix assumes the `__typename ` field will always be available. Are there cases where it is not? I know that for `_entities` queries we will have it (since we are sending a variable object containing id and __typename), but for other queries?

2022-02-15 16:00 UTC, garypen requested changes
A small suggestion to be DRY.

Also: regarding your question about `__typename` availability. This page says: https://www.apollographql.com/docs/apollo-server/schema/schema/#:~:text=GraphQL%20clients%20use%20an%20object's,every%20object%20of%20every%20query. My reading of that is that `__typename` is always present for all queries.

2022-02-15 16:00 UTC, garypen commented on apollo-router-core/src/spec/fragments.rs
> +                        .to_string();
Maybe create a function to get "type_condition" since you do the same thing in selection.rs? Also: maybe vary the strings for the two type expects?

2022-02-15 16:44 UTC, Geal commented
> Also: regarding your question about __typename availability. This page says: https://www.apollographql.com/docs/apollo-server/schema/schema/#:~:text=GraphQL%20clients%20use%20an%20object's,every%20object%20of%20every%20query. My reading of that is that __typename is always present for all queries.

oh, good to know, thanks

2022-02-16 08:55 UTC, bnjjj approved these changes

2022-02-16 10:52 UTC, Geal commented
so I've checked, and the query planner always adds the typename field, so we're fine here

2022-02-16 11:07 UTC, garypen approved these changes

2022-02-16 11:44 UTC, merged