return a better error when using defer in a subscription
apollographql/router pull request #4784
Opened 2024-03-11 16:01 UTC by bnjjj

Fixes #4783

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-03-11 16:03 UTC, lleadbet commented on apollo-router/src/services/supergraph/service.rs
> +                        .message("@defer is not supported on subscriptions")
```suggestion
                        .message("@defer is not supported within a subscription")
```

2024-03-12 14:37 UTC, abernix requested changes
Needs tests, but otherwise LGTM.

2024-03-12 15:38 UTC, goto-bus-stop reviewed
I think we should do this before calling into QP, and after Rust-based validation. Maybe we can do it as the first thing inside this `service_call` using the `ParsedDocument` on the context? Or even inside `CachingQueryPlanner`

2024-03-14 09:00 UTC, goto-bus-stop commented
Per discussion in Slack, the JS QP already does this check, but the error gets mangled on the way up from deno to the final response. A fix for that is here: https://github.com/apollographql/federation-rs/pull/457

2024-06-10 08:53 UTC, abernix commented
@bnjjj Did you want to bring this PR back to life? It seems useful intent?

2024-06-10 09:33 UTC, bnjjj commented
It's something that will be automatically fixed by the new QP so I think it's ok to just close it now and wait for the proper fix in the new QP

2024-06-10 09:33 UTC, closed without merging

2024-06-10 09:37 UTC, goto-bus-stop commented
I don't remember exactly but i think this is already done because of https://github.com/apollographql/federation-rs/pull/457 .

2024-06-10 10:08 UTC, abernix commented
thanks folks!