[docs] Add docs about span macros
apollographql/router pull request #4918
Opened 2024-04-04 17:34 UTC by smyrick

The docs reference the macros available but only mention how to use the metric ones when we do support the span macros too

2024-04-04 19:03 UTC, BrynCooke commented on docs/source/customizations/native.mdx
> +span!(target: "app_spans", Level::TRACE, "my span");
It's probably best to use info_span! as the level directly corresponds to the log level which most people will set to info.

2024-04-05 09:43 UTC, BrynCooke approved these changes

2024-04-05 17:30 UTC, shorgi requested changes

2024-04-05 17:30 UTC, shorgi commented on docs/source/customizations/native.mdx
> +To create custom metrics, traces, and spans you can use the [tracing macros](https://docs.rs/tracing/latest/tracing/index.html#macros) to generate events and logs.
```suggestion
To create custom metrics, traces, and spans, you can use [`tracing` macros](https://docs.rs/tracing/latest/tracing/index.html#macros) to generate events and logs.
```

2024-04-05 17:30 UTC, shorgi commented on docs/source/customizations/native.mdx
> +To create your custom metrics in [Prometheus](https://prometheus.io/) you can use the [event macros](https://docs.rs/tracing/latest/tracing/index.html#macros) to generate an event.
```suggestion
To create your custom metrics in [Prometheus](https://prometheus.io/) you can use [event macros](https://docs.rs/tracing/latest/tracing/index.html#macros) to generate an event.
```

2024-04-05 17:30 UTC, shorgi commented on docs/source/customizations/native.mdx
> +To create custom spans and traces you can use the [tracing macros](https://docs.rs/tracing/latest/tracing/index.html#macros) to generate a span.
```suggestion
To create custom spans and traces you can use [`tracing` macros](https://docs.rs/tracing/latest/tracing/index.html#macros) to generate a span.
```

2024-04-05 17:30 UTC, shorgi commented on docs/source/customizations/native.mdx
> +Make sure to [enable OpenTelemtry tracing](../configuration/telemetry/exporters/tracing/overview) in your configuration if you want to custom traces generated and linked by the Router.
```suggestion
Make sure to [enable OpenTelemetry tracing](../configuration/telemetry/exporters/tracing/overview) in your configuration if you want customize the traces generated and linked by the router.
```

2024-06-10 19:39 UTC, abernix commented
@shorgi Could you re-review? Thanks!

2024-06-10 20:39 UTC, shorgi approved these changes

2024-06-11 19:26 UTC, merged