Use the entire schema when hashing an introspection query
apollographql/router pull request #5007
Opened 2024-04-23 17:32 UTC by Geal

Fix #5006

in https://github.com/apollographql/router/pull/4883 we introduced a query hashing scheme that stays stable across schema updates if the update does not affect the query. unforutnately, it was not taking introspection queries into account.
This fixes the hashing mechanism to add the schema string to hashed data if we encounter an introspection field. This is a temporary fix until we move introspection execution out of query planning. At that point, this hashing mechanism won't ever see introspection fields.

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-04-24 08:43 UTC, o0Ignition0o approved these changes

2024-04-24 08:51 UTC, goto-bus-stop approved these changes

2024-04-24 17:49 UTC, abernix requested changes
If it's possible to add a test, that's my "requested change".  You're free to dismiss this review.

2024-04-25 11:19 UTC, o0Ignition0o commented
Fixed in [433ba4b](https://github.com/apollographql/router/pull/5007/commits/433ba4b891b375516fd9787cf68ae1583cfdf123)

2024-04-25 11:22 UTC, abernix approved these changes
Tests have been introduced. LGTM.  thank you, @o0Ignition0o

2024-04-25 16:41 UTC, merged