Add gt, gte, lt, lte, and range operations for telemetry conditions
apollographql/router pull request #5048
Opened 2024-04-29 22:58 UTC by tninesling

Add gt, gte, lt, lte, and range operations for telemetry conditions.

Fixes #**issue_number**

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [X] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [X] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-04-30 08:22 UTC, bnjjj commented
@tninesling Could you do this on top of https://github.com/apollographql/router/pull/5022 to also add support for `response_event` ?

2024-04-30 13:47 UTC, BrynCooke requested changes
Docs need updating:
https://github.com/apollographql/router/blob/dev/docs/source/configuration/telemetry/instrumentation/conditions.mdx

2024-05-03 07:15 UTC, BrynCooke approved these changes

2024-05-03 07:27 UTC, merged

2024-05-16 18:43 UTC, abernix commented on .changesets/feat_tninesling_telemetry_range_operators.md
> +By [@tninesling](https://github.com/tninesling) in https://github.com/apollographql/router/pull/5048
Post merge note: this bit shouldn't be in the changelog.  We'll remove in post on #5180.