fix(telemetry): do not create custom events if level is off
apollographql/router pull request #5165
Opened 2024-05-14 14:45 UTC by bnjjj

Don't create custom events and attributes if you set the level to `off` 

example of configuration:

```yaml
telemetry:
  instrumentation:
    events:
      router:
        # Standard events
        request: info
        response: info
        error: info

        # Custom events
        my.disabled_request_event:
          message: "my event message"
          level: off # Disabled because we set the level to off
          on: request
          attributes:
            http.request.body.size: true
```

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-05-14 15:25 UTC, garypen reviewed
Should we document it?

What I mean is this. We should either:
 - Explicitly enforce our documented interface by deliberately failing use of `off`
 - …OR… embrace the existence of `off` and document/support it.

Either option seems reasonable, but it probably is better to support `off` and document it.

2024-05-15 07:23 UTC, garypen approved these changes

2024-05-15 07:33 UTC, BrynCooke requested changes
I think this needs a test

2024-05-15 07:58 UTC, bnjjj commented
@BrynCooke It's already tested because I updated configuration test and the related snapshots having all the logs didn't change because these events are indeed disabled

2024-05-15 10:26 UTC, BrynCooke approved these changes

2024-05-15 11:20 UTC, merged