add support for studio trace id in selectors and document context entry
apollographql/router pull request #5189
Opened 2024-05-16 14:04 UTC by bnjjj

Add support for a new trace id selector kind, the apollo trace id which represents the trace id on [Apollo Studio](https://studio.apollographql.com/). 

Example:

```yaml
telemetry:
  instrumentation:
    spans:
      router:
        "studio.trace.id":
            trace_id:: apollo
```

Fixes #3803 
Fixes #5172

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-05-16 14:17 UTC, garypen commented on docs/source/customizations/rhai-api.mdx
> +You can access to provided constants, it's mainly context keys to use when you want to fetch data from the context.
```suggestion
You can access provided constants, it's mainly context keys to use when you want to fetch data from the context.
```

2024-05-16 16:23 UTC, garypen requested changes
I'm requesting change for the selectors.mdx change because I don't think that will work properly without escaping the pipe.
Apart from that it looks great and thanks for documenting the Rhai constants.

2024-05-17 08:28 UTC, bnjjj commented
@garypen good catch ! Thanks

2024-05-17 10:03 UTC, garypen approved these changes

2024-05-17 18:42 UTC, shorgi reviewed
Docs review

2024-05-17 18:42 UTC, shorgi commented on docs/source/customizations/rhai-api.mdx
> +You can access provided constants, it's mainly context keys to use when you want to fetch data from the context.
```suggestion
The router provides constants for your Rhai scripts that mostly help you fetch data from the context.
```

2024-05-17 18:42 UTC, shorgi commented on docs/source/configuration/telemetry/apollo-telemetry.mdx
> +If you're writing a plugin you can get the Studio Trace ID by reading the value of `apollo_operation_id` from the context.
```suggestion
If you're writing a plugin, you can get the Studio Trace ID by reading the value of `apollo_operation_id` from the context.
```

2024-05-17 18:42 UTC, shorgi commented on .changesets/feat_bnjjj_add_studio_trace_id_selector.md
> +Example:
Do separate issues require separate changelog entries? Can edit in the eventual release's changelog.

```suggestion
### Add support for studio trace id in selectors and document context entry ([Issue #3803](https://github.com/apollographql/router/issues/3803)), ([Issue #5172](https://github.com/apollographql/router/issues/5172))

Add support for a new trace ID selector kind, the `apollo` trace ID, which represents the trace ID on [Apollo GraphOS Studio](https://studio.apollographql.com/). 

An example configuration using `trace_id: apollo`:
```

2024-05-17 18:42 UTC, shorgi commented on .changesets/feat_bnjjj_add_studio_trace_id_selector.md
> +Add documentation for available rhai constants.
```suggestion
Also, router documentation has been updated with constants that are available in Rhai.
```

2024-05-17 18:42 UTC, shorgi commented on apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
> +          "description": "Apollo Studio trace id",
```suggestion
          "description": "Apollo Studio trace ID",
```

2024-05-21 15:18 UTC, BrynCooke reviewed
Can we introduce an integration test for this? I think it should jsut work as the apollo key and graph ref is present.

2024-05-23 15:45 UTC, bnjjj commented
@BrynCooke integration test added

2024-05-24 09:23 UTC, merged

2024-06-03 15:07 UTC, abernix commented on docs/source/customizations/rhai-api.mdx
> +
@shorgi Not urgent, but this probably needs some other visual treatment.

2024-06-03 17:54 UTC, abernix commented
I think this whole feature should have been called "operation ID"?  We pluck the value from `APOLLO_OPERATION_ID`; it's **not** a trace ID, right?