fix(telemetry): rename the selector to get studio operation id
apollographql/router pull request #5337
Opened 2024-06-04 15:10 UTC by bnjjj

We introduced a new `trace_id` selector format in `1.48.0` which has been misnamed because it's not a trace id but the Apollo Studio Operation ID. If you want to access to this selector, here is an example:

```yaml
telemetry:
  instrumentation:
    spans:
      router:
        "studio.operation.id":
            studio_operation_id: true
```

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [x] Documentation[^2] completed
- [x] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [x] Unit Tests
    - [x] Integration Tests
    - [x] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-06-04 15:22 UTC, garypen commented on docs/source/configuration/telemetry/instrumentation/selectors.mdx
> +| `trace_id`         | Yes         | `open_telemetry`\|`datadog`\              | The trace ID                         |
```suggestion
| `trace_id`         | Yes         | `open_telemetry`\|`datadog`              | The trace ID                         |
```

2024-06-04 15:23 UTC, Geal approved these changes

2024-06-04 15:55 UTC, bnjjj commented on docs/source/configuration/telemetry/instrumentation/selectors.mdx
> +| `trace_id`         | Yes         | `open_telemetry`\|`datadog`\              | The trace ID                         |
Raaah again !

2024-06-04 16:04 UTC, garypen approved these changes

2024-06-05 12:29 UTC, abernix commented
I think tests are failing for a legitimate reason here.

2024-06-05 12:30 UTC, abernix requested changes
Tests are failing because the rename isn't quite complete.

2024-06-05 14:47 UTC, abernix approved these changes

2024-06-05 14:52 UTC, merged