Feat/rhai uri port
apollographql/router pull request #5439
Opened 2024-06-13 17:28 UTC by lleadbet

This adds support to read the port in Rhai using the `request.uri.port` syntax, as well as setting the port when used in the `subgraph_service` hook. 

Fixes #5437

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [x] Changes are compatible[^1]
- [x] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

The function can return an empty result when the port is not explicitly set but can be checked for.

2024-08-19 15:33 UTC, bnjjj approved these changes

2024-08-27 10:45 UTC, abernix requested changes
Would like to have a testing strategy included.

2024-09-16 08:26 UTC, bnjjj commented
@lleadbet Could you add a test in the rhai file in `apollo-router/tests/fixtures/request_response_test.rhai`  to make sure it works properly please ?

2024-09-17 08:19 UTC, bnjjj approved these changes

2024-10-14 13:13 UTC, garypen approved these changes

2024-10-15 15:24 UTC, svc-apollo-docs commented
### ❌ Docs Preview Failed

Error
```
HttpError: Resource not accessible by personal access token - https://docs.github.com/rest/commits/statuses#create-a-commit-status
```

2024-10-15 15:28 UTC, bnjjj commented
Closing in favor of https://github.com/apollographql/router/pull/6153

2024-10-15 15:28 UTC, closed without merging