fix(telemetry): always create trace id even if the trace is not sampled
apollographql/router pull request #5447
Opened 2024-06-14 08:55 UTC by bnjjj

Now when using `experimental_response_trace_id` for example, you'll always have a valid trace_id in response headers even if the trace is not sampled. It's following the behavior of the [OpenTelemetry specs](https://opentelemetry.io/docs/specs/otel/trace/sdk/#sampling). 

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-06-14 09:41 UTC, bnjjj commented on apollo-router/src/plugins/telemetry/dynamic_attribute.rs
> +                            // FIXME: we should put event attributes somewhere else to make it work even if it's not sampled like we did with LogAttributes
I created the [related issue ](https://github.com/apollographql/router/issues/5448)

2024-06-14 09:41 UTC, bnjjj commented on apollo-router/src/plugins/telemetry/dynamic_attribute.rs
> +                            // FIXME: we should put event attributes somewhere else to make it work even if it's not sampled like we did with LogAttributes
Related [issue](https://github.com/apollographql/router/issues/5448) created

2024-06-14 10:25 UTC, BrynCooke requested changes
Can we add some tests to verify that the traceID is making it to the logging also?
Either in https://github.com/apollographql/router/blob/dev/apollo-router/tests/integration/telemetry/logging.rs or the jaeger tests.

2024-06-14 12:31 UTC, bnjjj commented
@BrynCooke Added 2 tests for json and text format with sampler set to `always_off` to make sure it works when it's sampled and not sampled https://github.com/apollographql/router/pull/5447/commits/e81d7cdfe7e0788499b2537fd78f4fe9bfedda25

2024-06-14 12:46 UTC, bnjjj commented
@BrynCooke Correct me if I'm wrong but I think this one will fix https://github.com/apollographql/router/issues/5387 right ?

2024-06-17 09:43 UTC, garypen approved these changes

2024-06-21 08:22 UTC, BrynCooke commented on apollo-router/src/plugins/telemetry/otel/layer.rs
> +        let sampled = if is_sampled {
Nice!

2024-06-21 08:31 UTC, BrynCooke approved these changes

2024-06-21 13:24 UTC, bnjjj commented on apollo-router/src/plugins/telemetry/config_new/events.rs
> +            ));
Events will always be displayed even if the span is not sampled. But I think one of improvement we can do here is to check if the user set the level `debug` we can know thanks to a helper in `tracing` I think and directly not collecting anything related to that event.

2024-06-21 13:39 UTC, merged