Entity cache: reorganize subgraph configuration override
apollographql/router pull request #5474
Opened 2024-06-18 13:14 UTC by Geal

*Description here*

Fixes #**issue_number**

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-06-25 15:19 UTC, bnjjj approved these changes
Missing a changelog, but otherwise LGTM

2024-06-26 07:40 UTC, garypen approved these changes

2024-06-26 07:43 UTC, IvanGoncharov approved these changes

2024-06-26 07:51 UTC, BrynCooke commented on apollo-router/src/plugins/cache/entity.rs
>      /// activates caching for all subgraphs, unless overriden in subgraph specific configuration
```suggestion
    /// Enable or disable the the entity caching feature
```

2024-06-26 08:31 UTC, BrynCooke requested changes

2024-06-26 08:33 UTC, BrynCooke commented
@Geal Can you make a generic struct to hold `all` and `subgraphs` that can be reused? You've mentioned before that we should have a standard way of doing this stuff and this would help us.

2024-06-26 08:45 UTC, Geal commented
> @Geal Can you make a generic struct to hold all and subgraphs that can be reused? You've mentioned before that we should have a standard way of doing this stuff and this would help us.
There is, it is called `SubgraphConfiguration`, it is used in this PR and defined here: https://github.com/apollographql/router/blob/dd9005e5cdca5090af049f2d236e3a3a47a89e34/apollo-router/src/configuration/subgraph.rs#L78-L88

2024-06-26 09:26 UTC, Geal commented
I made the following changes in [bfb7fbe](https://github.com/apollographql/router/pull/5474/commits/bfb7fbe0dd81be6886873c9bd8b5a3b7a5d08e2a) and [d36870d](https://github.com/apollographql/router/pull/5474/commits/d36870d968cb1b29209cdc1253ac010c0e158e57):
- the top level `enabled` is explicitely a precondition to enabling entity cache on any subgraph
- uses the `SubgraphConfiguration::get` method to fall back to the `all` configuration if the subgraph is not present (per field override between `all` and `subgraphs` is done in the `Deserialize` implementation)

2024-06-26 09:31 UTC, BrynCooke approved these changes

2024-06-26 09:43 UTC, merged