fix: misc graph_path display fixes
apollographql/router pull request #5481
Opened 2024-06-18 22:56 UTC by dariuszkuc

Fixes
* `SimultaneousPaths` should not wrap single element in redundant brackets `{ }`
* `OpGraphPath` added missing conditions to the edges

Before
```
{ --[key()]--> I(S1) --[__typename]--> String(S1) }
```

After
```
 --[{ id } ⊢ key()]--> I(S1) --[__typename]--> String(S1)
```

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-06-18 23:15 UTC, dariuszkuc commented
There is still a mismatch in how we display graph paths
* JS always adds the head info, e.g. above path should be ` I(S2) --[{ id } ⊢ key()]--> I(S1) --[__typename]--> String(S1)`
* root nodes are not printed correctly, e.g. 
```
Query(S2) --[iFromS2]--> I(S2) --[{ __typename } ⊢ ... on A]--> I(S2) --[y]--> Int(S2)
// vs
[query](_)* --[iFromS2]--> I(S2) --[{ __typename } ⊢ ... on A]--> I(S2) --[y]--> Int(S2)
```

Display for `QueryGraphNode` seems [correct](https://github.com/apollographql/router/blob/v1.49.0/apollo-federation/src/query_graph/mod.rs#L77-L88) but we format the type [incorrectly](https://github.com/apollographql/router/blob/v1.49.0/apollo-federation/src/query_graph/mod.rs#L96-L105) with extra `[]` brackets and lowercase string which is [derived](https://github.com/apollographql/router/blob/dev/apollo-federation/src/schema/position.rs#L1259-L1266).

Questions
* graph node source is `_` -> should it be pointing to S2?
```
QueryGraphNode { type_: FederatedRootType(Query), source: "_", has_reachable_cross_subgraph_edges: true, provide_id: None, root_kind: Some(Query) }
```
* interestingly even though it is root vertex why don't don't we print the `*` in the JS version?

2024-06-19 00:47 UTC, duckki commented on apollo-federation/src/query_graph/graph_path.rs
> +            [first] => f.write_fmt(format_args!("{first}")),
It's my bad. Nice catch!

2024-06-19 00:58 UTC, duckki requested changes
The change looks good!

This part doesn't look inconsistent with JS version, which might be related to your question.
```rust
        if head.root_kind.is_some() {
            write!(f, "{head}")?;
        }
```

The JS version (below) does NOT print the head if it is root (see the last line).
If the head is root, it's skipped and the first edge's tail is printed first without the arrow.

```js
  toString(): string {
    const isRoot = isRootVertex(this.root);
    if (isRoot && this.size === 0) {
      return '_';
    }
    const pathStr = this.mapMainPath((edge, idx) => {
      if (edge) {
        if (isRoot && idx == 0) {
          return edge.tail.toString();
        }
        const label = edge.label();
        return ` -${label === "" ? "" : '-[' + label + ']-'}-> ${edge.tail}`
      }
      return ` (${this.props.edgeTriggers[idx]}) `;
    }).join('');
    const deferStr = this.deferOnTail ? ` <defer='${this.deferOnTail.label}'>` : '';
    const typeStr = this.props.runtimeTypesOfTail.length > 0 ? ` (types: [${this.props.runtimeTypesOfTail.join(', ')}])` : '';
    return `${isRoot ? '' : this.root}${pathStr}${deferStr}${typeStr}`;
  }
```

2024-06-19 02:10 UTC, dariuszkuc commented
Yeah I was looking into this a bit more and the JS code
- by default it adds the root node IF it is not root -> 
```
return `${isRoot ? '' : this.root}${pathStr}${deferStr}${typeStr}`;
```

There is a difference in closed branches though
- in JS we start at (head) `[query](_)*` (entry to supergraph) so when iterating over the edges (always start with head) -> if it `isRoot` we just use the [tail of the edge](https://github.com/apollographql/federation/blob/%40apollo/subgraph%402.8.1/query-graphs-js/src/graphPath.ts#L891) (without any labels which is just a vertex and results in the `Query(S2)` entry point) 
- in RS side of things we do start at the supergraph entry but it appears that we are missing this extra `Query(S2)` node

2024-06-19 02:37 UTC, dariuszkuc commented on apollo-federation/src/query_graph/graph_path.rs
> +                        write!(f, "{node}")
this still adds extra `*` at the end of the subgraph transition node i.e. `Query(S2)` vs `Query(S2)*`

2024-06-19 02:38 UTC, dariuszkuc commented on apollo-federation/src/query_graph/graph_path.rs
> +                        write!(f, "{node}")
seems like a bug as in JS that node is not marked as root

2024-06-20 00:02 UTC, duckki approved these changes
This display fix looks good to me!

2024-06-20 16:10 UTC, dariuszkuc commented on apollo-federation/src/query_graph/graph_path.rs
> +                        write!(f, "{node}")
we were incorrectly looking at the `root_kind` struct field  vs `is_root_node()` function value

2024-06-20 17:06 UTC, merged