Ds/k8 config addition
apollographql/router pull request #5672
Opened 2024-07-16 15:35 UTC by daljitsumman

A simple set of changes to the service and values file as required by customer

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-07-22 08:20 UTC, BrynCooke requested changes
`helm/chart/router/README.md` needs updating with these additions

2024-07-22 14:58 UTC, garypen commented
> `helm/chart/router/README.md` needs updating with these additions

Not required. This will happen automatically during release when we invoke `helm-docs`.

2024-07-24 13:41 UTC, garypen reviewed
Please add a changeset to the PR following the instructions in `.changesets/README.md`.
also: please make the PR title a little more descriptive.

2024-11-21 14:24 UTC, svc-apollo-docs commented
### 🛠️ Docs Preview Building...

<details>
<summary>Configuration</summary>

```json
{
  "repoOverrides": {
    "apollographql/router@dev": {
      "remote": {
        "owner": "daljitsumman",
        "repo": "router",
        "branch": "ds/k8-config-addition"
      }
    }
  }
}
```

</details>

7dff24ade81998cd73ba99922a54035fbee988b9

2024-11-21 14:26 UTC, daljitsumman commented
Hi @garypen, have created the required changeset. If anything missed please let me know. Thanks.

2025-02-14 14:12 UTC, BrynCooke commented on helm/chart/router/templates/service.yaml
> +  {{- with .Values.service.annotations }}
I don't see annotations as part of the service spec schema:
https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.6.4-local/servicespec.json

The annotations are already in the metadata. I think these will be ignored?

2025-02-14 15:47 UTC, BrynCooke commented on helm/chart/router/templates/service.yaml
> +  {{- with .Values.service.annotations }}
I made the change direct to this branch. Approved, so just waiting if you agree.

2025-02-14 15:47 UTC, BrynCooke approved these changes

2025-02-14 16:59 UTC, garypen approved these changes

2025-02-14 16:59 UTC, garypen commented on helm/chart/router/templates/service.yaml
> +
```suggestion
```

2025-02-14 18:23 UTC, abernix commented
@mergifyio backport 1.x

2025-02-17 09:16 UTC, BrynCooke commented
I'm bringing this PR into the router repo https://github.com/apollographql/router/pull/6804

2025-02-17 09:16 UTC, closed without merging