add more attributes and include invalidation api endpoint as a root trace to be sampled
apollographql/router pull request #5746
Opened 2024-07-30 13:47 UTC by bnjjj

2024-07-31 08:12 UTC, BrynCooke requested changes
No test has changed in this PR.
As there are existing integration tests for cache invalidation I think some minor modification to the yaml test harness may get us there.

2024-07-31 14:30 UTC, bnjjj commented
There is no tracing test for invalidation cache ATM

2024-10-30 16:46 UTC, Geal approved these changes

2024-11-20 09:18 UTC, BrynCooke commented
@bnjjj What do we want to do with this? I think we should add some tests if we don't have any for cache invalidation.

2024-11-20 09:29 UTC, BrynCooke approved these changes

2024-11-20 09:53 UTC, merged