fix(federation): use supergraph when parsing requires fieldset
apollographql/router pull request #5823
Opened 2024-08-14 18:52 UTC by dariuszkuc

When parsing `@requires` field set selection we need to use supergraph schema instead of a target subgraph schema.

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-08-15 07:23 UTC, goto-bus-stop commented on apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
> +                (fields, parent_type_pos, false)
I would instead write `(fields, parent_type_pos, &schema)` here and `(fields, parent_type_pos, &supergraph_schema)` below. Then you don't need the if/else to populate `fields` later.

2024-08-15 09:17 UTC, lrlna requested changes
Can you add a test for this?

2024-08-15 23:38 UTC, duckki approved these changes
The code change and test look good.
I confirmed the test reproduces the issue and the PR eliminates the known errors from the corpus.

2024-08-16 07:26 UTC, lrlna approved these changes

2024-08-16 07:26 UTC, merged