Add OTEL information for operation limits
apollographql/router pull request #5884
Opened 2024-08-26 19:16 UTC by andrewmcgivery

Add OTEL information for operation limits

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [x] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-08-26 19:52 UTC, andrewmcgivery commented
Docs build actually did success on retry! 😅 https://deploy-preview-5884--apollo-router-docs.netlify.app/configuration/operation-limits

2024-08-26 20:31 UTC, shorgi approved these changes

2024-08-26 20:31 UTC, shorgi commented on docs/source/configuration/operation-limits.mdx
> +It may be difficult to decide what values to set for operation limits if you have a large number of existing operations. A good option to help make this decision is to measure incoming operations for
```suggestion
Router telemetry can help you set operation limits, especially when you have a large number of existing operations. You can measure incoming operations over a fixed duration, then use the captured data as a baseline configuration.
```

2024-08-26 20:31 UTC, shorgi commented on docs/source/configuration/operation-limits.mdx
> +## Measuring for appropriate values with telemetry
```suggestion
## Using telemetry to set operation limits
```

2024-08-26 20:31 UTC, shorgi commented on docs/source/configuration/operation-limits.mdx
> +You can configure the Router with a [custom event](https://www.apollographql.com/docs/router/configuration/telemetry/instrumentation/events#custom-events) to log the values of aliases, depth, height,
```suggestion
To log limit information about every operation, you can configure the router with a [custom event](/router/configuration/telemetry/instrumentation/events#custom-events) to log the values of aliases, depth, height, and root_fields for each operation:
```

2024-08-26 20:31 UTC, shorgi commented on docs/source/configuration/operation-limits.mdx
> +This may not be a good model for a large amount of traffic so it may be preferred to instead collect metrics and export them to your APM.
```suggestion
<Note>

For a large amount of traffic, you may prefer to collect and export metrics to your APM instead.

</Note>
```

2024-08-26 20:31 UTC, shorgi commented on docs/source/configuration/operation-limits.mdx
> +You can configure the Router to collect [custom metrics](/router/configuration/telemetry/instrumentation/instruments#custom-instruments) on the values of aliases, depth, height, and root_fields on ea
```suggestion
To capture and view metrics to help set your operation limits, you can configure the router to collect [custom metrics](/router/configuration/telemetry/instrumentation/instruments#custom-instruments) on the values of aliases, depth, height, and root_fields for each operation:
```

2024-08-26 20:31 UTC, shorgi commented on docs/source/configuration/operation-limits.mdx
> +You should also configure the Router to [export metrics](/router/configuration/telemetry/exporters/metrics/overview) to your APM tool.
```suggestion
You should also configure the router to [export metrics](/router/configuration/telemetry/exporters/metrics/overview) to your APM tool.
```

2024-08-27 15:13 UTC, bnjjj requested changes

2024-08-27 15:13 UTC, bnjjj commented on docs/source/configuration/operation-limits.mdx
> +```
```suggestion
```yaml title="router.yaml"
```

2024-08-27 15:13 UTC, bnjjj commented on docs/source/configuration/operation-limits.mdx
> +```
```suggestion
```yaml title="router.yaml"
```

2024-08-27 15:13 UTC, bnjjj commented on .changesets/docs_feature_operationlimitsotel.md
> +Add OTEL information for operation limits to docs.
```suggestion
Add OTEL (OpenTelemetry) information for operation limits to docs.
```

2024-08-27 15:53 UTC, merged