Added telemetry for Rhai usage
apollographql/router pull request #6027
Opened 2024-09-18 16:41 UTC by andrewmcgivery

Added telemetry for Rhai usage

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-09-19 15:11 UTC, BrynCooke requested changes
Please can you add a test? There is an existing test already, you just need to add a config file to `src/configuration/testdata/metrics` and commit the snapshot.

2024-09-20 14:32 UTC, BrynCooke approved these changes

2024-09-24 08:20 UTC, garypen approved these changes

2024-09-26 08:07 UTC, bnjjj approved these changes

2024-10-01 15:37 UTC, merged

2024-10-01 18:00 UTC, abernix commented
Tests passed in https://github.com/apollographql/router/pull/6098.  This is now merged into `dev`.