chore: Quality of Life: xtask all improvements.
apollographql/router pull request #604
Opened 2022-03-09 14:50 UTC by o0Ignition0o

`cargo xtask all` will now actually format your code and apply the license update for you!

2022-03-09 16:10 UTC, garypen requested changes
I'm not sure if my comments are correct, but I'm asking anyway.

2022-03-09 16:55 UTC, o0Ignition0o commented on xtask/src/commands/lint.rs
> +        Ok(())
Totally agree it doesn't read well, let's see if i can do better.

Basically what i m trying to convey is "run cargo fmt --check. if it fails, notify the developper they will have a diff and they shall commit it, and run the actual cargo fmt"

2022-03-09 16:57 UTC, o0Ignition0o commented on xtask/src/commands/all.rs
> +        self.compliance.run_local()
if someone checks in badly formatted code, the ci will run `cargo xtask lint` (and not `cargo xtask all`) which will run `cargo fmt --check` and fail the CI

2022-03-11 10:44 UTC, Geal commented on xtask/src/commands/all.rs
> +        self.compliance.run_local()
yup, it helps locally but the CI guarantees everything

2022-03-11 10:45 UTC, Geal approved these changes

2022-04-04 09:27 UTC, merged