Add router config validate subcommand
apollographql/router pull request #6131
Opened 2024-10-08 21:54 UTC by andrewmcgivery

Add `router config validate` subcommand to allow validation of a Router config file without fully starting up the Router.

```
./router config validate <path-to-config-file.yaml>
```

Note: Didn't see any examples of how to directly unit test commands.. but I tested manually! 😅 

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [x] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

[ROUTER-1059]: https://apollographql.atlassian.net/browse/ROUTER-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-08 21:54 UTC, svc-apollo-docs commented
### ❌ Docs Preview Failed

Error
```
HttpError: Resource not accessible by personal access token - https://docs.github.com/rest/commits/statuses#create-a-commit-status
```

2024-10-10 20:40 UTC, andrewmcgivery commented on apollo-router/src/executable.rs
> +                .validate()?;
Sorry, not understanding your comment 😓 

Are you saying that this code does more than just validate the Router config file?

2024-11-06 17:02 UTC, theJC commented
Indeed is anxiously awaiting for this support to be added to improve our pipelines and shift left bad config as much as possible.  

Based on the feedback, I believe there is just a documentation concern about indicating the scope of what it can validate and what it cannot.    Any chance we can get this over the finish line with just a doc update?

2024-11-07 10:08 UTC, bnjjj commented on apollo-router/src/executable.rs
> +                .validate()?;
I'm just saying that on plugins we have other config validations. For example [here](https://github.com/apollographql/router/blob/dev/apollo-router/src/plugins/telemetry/mod.rs#L294:L294) which validate that the config is logically correct, not only syntactically. So what I would like to have is to document that your new config validate will only validate it's syntactically correct regarding the json schema. That's all

2025-01-08 20:43 UTC, andrewmcgivery commented on apollo-router/src/executable.rs
> +                .validate()?;
Updated!

2025-01-13 11:34 UTC, bnjjj requested changes

2025-01-13 11:34 UTC, bnjjj commented on docs/source/reference/router/configuration.mdx
> +Note: This is a static validation that checks if it is syntactically using the JSON schema. The router does additional logical checks on startup against the config that this command does not capture.
```suggestion
Note: This is a static validation that checks if it is syntactically correct using the JSON schema. The router does additional logical checks on startup against the config that this command does not capture.
```

2025-01-14 08:19 UTC, bnjjj approved these changes

2025-02-14 16:04 UTC, BrynCooke approved these changes

2025-02-14 16:05 UTC, BrynCooke commented
@andrewmcgivery Sorry this took so long to review. If you have time to resolve the conflicts we can merge right away.

2025-03-17 20:36 UTC, andrewmcgivery commented
Closing in favor of https://github.com/apollographql/router/pull/7016 as this branch is far too stale.

2025-03-17 20:36 UTC, closed without merging