Remove experimental_when_header feature
apollographql/router pull request #6285
Opened 2024-11-19 15:35 UTC by bnjjj

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-11-19 15:35 UTC, svc-apollo-docs commented
### 🛠️ Docs Preview Building...

<details>
<summary>Configuration</summary>

```json
{
  "repoOverrides": {
    "apollographql/router@next": {
      "remote": {
        "owner": "apollographql",
        "repo": "router",
        "branch": "bnjjj/fix_786"
      }
    }
  }
}
```

</details>

4f52dea9e46330507675ff343f31953834b4fef0

2024-11-19 15:35 UTC, abernix commented
@bnjjj @garypen Does this get a place in some section of the migration guide?

2024-11-20 08:59 UTC, bnjjj commented
@abernix Yes. Do we have an existing one somewhere ?

2024-11-20 11:09 UTC, abernix commented
@bnjjj Yup! https://github.com/apollographql/router/blob/next/docs/source/reference/migration/from-router-v1.mdx

2024-11-20 14:54 UTC, garypen requested changes
Needs an entry in the migration guide.

2024-11-20 14:54 UTC, garypen commented on apollo-router/src/plugins/telemetry/config_new/logging.rs
>  impl Logging {
I think we could remove this completely.

2024-11-20 14:54 UTC, garypen commented on apollo-router/tests/integration/lifecycle.rs
> -#[tokio::test(flavor = "multi_thread")]
Is this a test we should retain but use a different experimental feature for testing?

2024-11-21 13:28 UTC, bnjjj commented on docs/source/reference/router/telemetry/instrumentation/selectors.mdx
> +| `supergraph_request_header` | Yes         |                  | The name of a supergraph request header                                        |
I'll add it on `dev` too

2024-11-21 14:12 UTC, garypen commented on docs/source/reference/migration/from-router-v1.mdx
> +This feature not longer exists and can be replaced with another one included in custom telemetry. Here is an example on how you could have the same behavior with the new configuration:
```suggestion
This feature no longer exists and can be replaced with another one included in custom telemetry. Here is how you would configure custom telemetry to achieve the same result:
```

2024-11-21 17:19 UTC, garypen approved these changes

2024-11-22 14:35 UTC, bnjjj commented on docs/source/reference/router/telemetry/instrumentation/selectors.mdx
> +| `supergraph_request_header` | Yes         |                  | The name of a supergraph request header                                        |
https://github.com/apollographql/router/pull/6327

2024-11-22 14:51 UTC, merged