plugins/fleet_detector: detect request/response sizes
apollographql/router pull request #6415
Opened 2024-12-09 11:47 UTC by nmoutschen

Add new metrics to report on subgraph fetches, and request/response sizes for both supergraph and subgraph operations.

---

**Checklist**

Complete the checklist (and note appropriate exceptions) before the PR is marked ready-for-review.

- [ ] Changes are compatible[^1]
- [ ] Documentation[^2] completed
- [ ] Performance impact assessed and acceptable
- Tests added and passing[^3]
    - [ ] Unit Tests
    - [ ] Integration Tests
    - [ ] Manual Tests

**Exceptions**

*Note any exceptions here*

**Notes**

[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do this.
[^2]: Configuration is an important part of many changes. Where applicable please try to document configuration examples.
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) in the Exceptions.

2024-12-09 11:48 UTC, svc-apollo-docs commented
### 🛠️ Docs Preview Building...

<details>
<summary>Configuration</summary>

```json
{
  "repoOverrides": {
    "apollographql/router@dev": {
      "remote": {
        "owner": "apollographql",
        "repo": "router",
        "branch": "nicolas/FLEET-20"
      }
    }
  }
}
```

</details>

c2745a93a318251e329cd219f234257603634f97

2024-12-10 09:06 UTC, bnjjj reviewed
It needs tests to make sur it works as expected

2024-12-10 09:06 UTC, bnjjj commented on apollo-router/src/plugins/fleet_detector.rs
> +                    router::Body::wrap_stream(body.map(move |res| {
We probably just need https://docs.rs/futures/latest/futures/prelude/stream/trait.StreamExt.html#method.inspect

2024-12-10 09:06 UTC, bnjjj commented on apollo-router/src/plugins/fleet_detector.rs
> +                        res.map(move |bytes| {
https://docs.rs/futures/latest/futures/prelude/stream/trait.StreamExt.html#method.inspect

2024-12-10 09:06 UTC, bnjjj commented on apollo-router/src/plugins/fleet_detector.rs
> +                            res.map(move |bytes| {
https://docs.rs/futures/latest/futures/prelude/stream/trait.StreamExt.html#method.inspect

2024-12-10 09:06 UTC, bnjjj commented on apollo-router/src/plugins/fleet_detector.rs
> +                            http.response.status_code = 0i64
Should we just mark it as an error without the status_code ?

2024-12-10 09:44 UTC, jonathanrainer approved these changes
LGTM

2024-12-10 09:45 UTC, loshz approved these changes

2024-12-10 11:03 UTC, BrynCooke requested changes
Needs tests.

2024-12-10 14:12 UTC, bnjjj requested changes

2024-12-10 14:12 UTC, bnjjj commented on apollo-router/src/plugins/fleet_detector.rs
> +                    KeyValue::new("subgraph.service.name", "subgraph"),
Nit: can we make sure to use `subgraph.name` instead to be consistent with what we have in the [official subgraph attributes](https://www.apollographql.com/docs/graphos/reference/router/telemetry/instrumentation/standard-attributes#subgraph)

2024-12-10 14:22 UTC, bnjjj approved these changes

2024-12-10 15:16 UTC, merged