First draft of a backpressure enabled pipeline
apollographql/router pull request #6486
Opened 2024-12-18 17:14 UTC by garypen

There's a long way to go, but some interesting aspects of the required changes are implemented here.

I noted that a significant number of errors and glitches and tests are resolved by making these changes. Mainly places where we were calling a service without readying it first or places where we were cloning an inner service without doing the memory "replace" dance.

Because we are using a "trick" to make the router service cloneable right now, there are a few tests which don't work properly. I think for the "full" work, we'll need to make the router service properly cloneable (without requiring a mutex).

This will require some fairly substantial re-working of a wide variety of services and layers. On the plus side, once we've done that work we'll be able to retire a bunch of code that we've written that we will no longer require.

I'll pick this up in the New Year...

2024-12-18 17:14 UTC, svc-apollo-docs commented
### 🛠️ Docs Preview Building...

<details>
<summary>Configuration</summary>

```json
{
  "repoOverrides": {
    "apollographql/router@next": {
      "remote": {
        "owner": "apollographql",
        "repo": "router",
        "branch": "garypen/next-backpressure"
      }
    }
  }
}
```

</details>

bef536737d8915259aa58ec5c2c88bdc8c2a6d49

2025-01-13 11:00 UTC, bnjjj commented on apollo-router/src/services/router/service.rs
> +        self.sb.lock().clone()
We should document why it's ok to lock the mutex here

2025-01-13 11:00 UTC, bnjjj commented on apollo-router/src/services/router/service.rs
> +            .buffer(50_000)
Can't we just apply the buffer only on static_page ?

2025-01-14 14:28 UTC, garypen commented on apollo-router/src/services/router/service.rs
> +            .buffer(50_000)
Probably. I'm also hopeful that we could modify static_page to be `Clone` and avoid the Buffer completely. We aren't quite at that stage of the work yet. Still trying to get tests to pass.

2025-01-14 14:29 UTC, garypen commented on apollo-router/src/services/router/service.rs
> +        self.sb.lock().clone()
Yes and in SupergraphCreator. I will do that before marking this PR ready to review.

2025-01-21 12:10 UTC, garypen commented on apollo-router/src/services/router/service.rs
> +            .buffer(50_000)
I looked into this at some length and it's actually SyncCheckpoint which we would need to modify to be `Clone` and we can't, because if we did, we would need to modify all our plugin interfaces to be `BoxCloneService` rather than `BoxService`.

I think this is something we won't be able to fix in router 2.0.

2025-01-24 11:59 UTC, BrynCooke commented on .changesets/feat_garypen_next_backpressure.md
> +In Router 1.x, back-pressure was not maintained. Requests would be accepted by the router. This could cause issue for routers which were accepting high levels of traffic.
Lets go into more detail about the benefits

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/axum_factory/tests.rs
> -async fn test_supergraph_timeout() {
This has been replaced by a test in traffic shaping

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/layers/async_checkpoint.rs
> -pub struct OneShotAsyncCheckpointService<S, Fut, Request>
This has been removed because it doesn't work this service expects only to be called once. We are now reusing services.

It's pub so we need to add it to the migration guide.

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/layers/async_checkpoint.rs
>          let service_stack = ServiceBuilder::new()
Let's create a ticket to migrate custom layers to use tower_test.

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/plugins/authorization/mod.rs
> +                    // XXX(@goto-bus-stop): Why are we doing this here, as opposed to the
Let's create a ticket for this

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/plugins/cache/entity.rs
> +        Poll::Ready(Ok(()))
Should be calling `service.poll_ready`

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/plugins/cache/entity.rs
> +            return self.service.ready().await?.call(request).await;
Remove the `ready().await?`. Plus other occurences.

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/plugins/limits/layer.rs
> +///
@BrynCooke TODO. Look at BodyLimit in more detail.

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/plugins/traffic_shaping/deduplication.rs
>      async fn dedup(
@BrynCooke Look in detail

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/plugins/traffic_shaping/deduplication.rs
> +            Box::pin(async move { inner.oneshot(request).await })
```suggestion
            Box::pin(async move { inner.call(request).await })
```

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/plugins/traffic_shaping/mod.rs
> +                .load_shed()
@BrynCooke Let's try and stick to the pattern in the router service

2025-01-24 11:59 UTC, BrynCooke commented on apollo-router/src/query_planner/tests.rs
> -    mock_products_service.expect_call().times(1).withf(|_| {
Possibly points to a bug. The original assertion placement was correct because the original service should be consumed.

2025-01-24 15:19 UTC, BrynCooke requested changes

2025-01-24 15:19 UTC, BrynCooke commented on apollo-router/src/services/router/service.rs
> +    sb: Arc<parking_lot::Mutex<router::BoxCloneService>>,
@BrynCooke Maybe this could be just buffer rather than in a mutex.

2025-01-24 15:19 UTC, BrynCooke commented on apollo-router/tests/integration/traffic_shaping.rs
> +    assert!(response.contains("GATEWAY_TIMEOUT"));
@BrynCooke Fixup these tests to use http.server.response metrics on status.

2025-01-24 16:13 UTC, goto-bus-stop commented on apollo-router/src/services/router/service.rs
> +                        self.supergraph_service.oneshot(request).await?
I'll write down how I understand it right now after our discussion:
`self.supergraph_service` here is a clone of the service that was readied in `RouterService::poll_ready`. Clones are un-ready by default, so this `self.supergraph_service` is actually *not* ready, which is why we need to oneshot it here. That technically breaks backpressure, but because we are still readying the supergraph service before calling into the router service, backpressure is actually still exerted at that point--there's just potential for some requests to slip through the cracks and end up queueing up at this `.oneshot()` call.

2025-01-24 16:29 UTC, BrynCooke commented on apollo-router/src/services/router/service.rs
> +    sb: Arc<parking_lot::Mutex<router::BoxCloneService>>,
We can get rid of the mutex. It requires an extra box, either on the service after it's cloned or on the future. I don't have strong feeling here.

2025-01-24 16:34 UTC, garypen commented on apollo-router/src/layers/async_checkpoint.rs
>          let service_stack = ServiceBuilder::new()
https://apollographql.atlassian.net/browse/ROUTER-984

2025-01-24 16:36 UTC, garypen commented on apollo-router/src/plugins/authorization/mod.rs
> +                    // XXX(@goto-bus-stop): Why are we doing this here, as opposed to the
https://apollographql.atlassian.net/browse/ROUTER-985

2025-01-24 16:47 UTC, garypen commented on apollo-router/src/plugins/cache/entity.rs
> +        Poll::Ready(Ok(()))
There is no `service` to call here, since this is the end of the chain. This is correct if you look at what the call function does.

It basically clones itself, then uses the clone to drive the service.

2025-01-24 16:48 UTC, garypen commented on .changesets/feat_garypen_next_backpressure.md
> +In Router 1.x, back-pressure was not maintained. Requests would be accepted by the router. This could cause issue for routers which were accepting high levels of traffic.
Done, but most of the details will be in the migration guide.

2025-01-24 16:50 UTC, garypen commented on apollo-router/src/plugins/traffic_shaping/deduplication.rs
> +            Box::pin(async move { inner.oneshot(request).await })
Done

2025-01-24 16:55 UTC, garypen commented on apollo-router/src/services/hickory_dns_connector.rs
>          let resolver = self.0.clone();
I've put the resolver in an Arc.

2025-01-24 16:58 UTC, garypen commented on apollo-router/src/services/http/service.rs
> -            _ => Either::Left(self.http_client.clone()),
https://apollographql.atlassian.net/browse/ROUTER-986

2025-01-24 16:59 UTC, garypen commented on apollo-router/src/services/layers/apq.rs
> +    /// Supergraph service implementation for Automatic Persisted Queries.
done.

2025-01-24 17:01 UTC, garypen commented on apollo-router/src/services/layers/content_negotiation.rs
> +// with JSON, but maybe this should be done as close as possible to where we populate the response body..?
https://apollographql.atlassian.net/browse/ROUTER-987

2025-01-24 17:05 UTC, garypen commented on apollo-router/src/services/router/service.rs
> +                        self.supergraph_service.oneshot(request).await?
I've added this comment to the source.

2025-01-27 08:48 UTC, garypen commented on apollo-router/src/services/router/service.rs
> +    sb: Arc<parking_lot::Mutex<router::BoxCloneService>>,
done: 9b7542300e03fc18de7d0a2447703af322169a55

2025-01-27 08:49 UTC, garypen commented on apollo-router/src/plugins/cache/entity.rs
> +        Poll::Ready(Ok(()))
Ignore my comment. I fixed this: 017b0f1e3fc88855b14ddcfc513fa2415bedbc11

2025-01-27 10:59 UTC, goto-bus-stop commented on apollo-router/src/query_planner/tests.rs
> -    mock_products_service.expect_call().times(1).withf(|_| {
The change is because service "creation" is now actually a clone (inside MakeSubgraphService::make). So that seems fine. The test as a whole is a bit odd and I need a bit longer to wrap my head around what it's really trying to do.

2025-01-27 11:19 UTC, BrynCooke commented on apollo-router/src/plugins/limits/layer.rs
> +///
Fixed in [f5d3bdb](https://github.com/apollographql/router/pull/6486/commits/f5d3bdb4bd96fbdc18ab16a9c00c44b0345a1428)

2025-01-27 12:33 UTC, BrynCooke commented on apollo-router/tests/integration/traffic_shaping.rs
> +    assert!(response.contains("GATEWAY_TIMEOUT"));
[8ea3123](https://github.com/apollographql/router/pull/6486/commits/8ea31233935e9b5d717d61e07dddf0b191cec2ef)

2025-01-27 13:50 UTC, BrynCooke commented on apollo-router/src/plugins/traffic_shaping/deduplication.rs
>      async fn dedup(
I think Dedupe is OK. We can tackle the performance issues it causes in a follow-up

2025-01-27 14:02 UTC, BrynCooke approved these changes

2025-01-27 14:02 UTC, BrynCooke commented on apollo-router/src/plugins/traffic_shaping/mod.rs
> +                .load_shed()
This can be done later.

2025-01-27 15:45 UTC, merged