[WIP] docs: instrumentation examples
apollographql/router pull request #6487
Opened 2024-12-18 22:06 UTC by shorgi

2024-12-18 22:06 UTC, svc-apollo-docs commented
### 🛠️ Docs Preview Building...

<details>
<summary>Configuration</summary>

```json
{
  "repoOverrides": {
    "apollographql/router@dev": {
      "remote": {
        "owner": "apollographql",
        "repo": "router",
        "branch": "eh/DOC-246/tlm-usecases"
      }
    }
  }
}
```

</details>

e96c3dd783f41276700383c7942b5576791e99a1

2024-12-18 22:35 UTC, shorgi commented
!docs preview main

2024-12-19 15:31 UTC, shorgi commented
!docs preview main

2024-12-20 00:06 UTC, shorgi commented
!docs preview main

2025-01-07 14:05 UTC, BrynCooke requested changes

2025-01-07 14:05 UTC, BrynCooke commented on docs/source/reference/router/telemetry/instrumentation/selectors.mdx
> +Configuring selectors with JSON paths, such as supergraph `response_data` and `response_errors`:
This will create a high cardinality metric:

A better example is this:
```
telemetry:
  exporters:
    metrics:
      prometheus:
        enabled: true
  instrumentation:
    instruments:
      supergraph:
        my.request.on_graphql_error:
          value: event_unit
          type: counter
          unit: error
          description: my description
          condition:
            exists:
              response_errors: "$.[0].extensions.code"
          attributes:
            response_errors:
              response_errors: "$.[0].extensions.code"
```

2025-01-09 20:04 UTC, BrynCooke approved these changes

2025-01-10 20:15 UTC, merged