Geal/clean up dedup on cancel
apollographql/router pull request #758
Opened 2022-03-30 09:00 UTC by Geal

Fix #754

This takes care of cleaning up the wait map by using a oneshot channel as drop signal. This is a pattern that I used a lot in [pulsar-rs](https://github.com/wyyerd/pulsar-rs) to perform async tasks on drop

2022-03-30 09:01 UTC, Geal commented
hmm, looks like I created this branch from the wrong one :sweat_smile: 

I'll clean that up. The relevant code is in https://github.com/apollographql/router/pull/758/commits/f261ff944f53a517ad07cd48f8d1156e5c63a63f

2022-03-30 09:48 UTC, BrynCooke commented on apollo-router-core/src/layers/deduplication.rs
> +                        let (_drop_signal, drop_sentinel) = oneshot::channel::<()>();
Nit: could be a mutex rather than a channel.

2022-03-30 09:51 UTC, BrynCooke approved these changes
LGTM

2022-03-31 10:04 UTC, garypen requested changes
We should also update: https://github.com/apollographql/router/blob/main/apollo-router-core/src/cache.rs
to maintain consistency.

2022-03-31 13:14 UTC, Geal commented
`cache.rs` is a bit tricky with the two locks, I'll send it in a separate PR so we can take the time to study it

2022-04-01 09:06 UTC, Geal commented
can we agree to merge this one at least?

2022-04-04 08:40 UTC, garypen approved these changes

2022-04-04 08:42 UTC, merged