fix: Cleanly shutdown the Telemetry plugin.
apollographql/router pull request #848
Opened 2022-04-13 17:12 UTC by o0Ignition0o

fixes #847

The telemetry plugin would cause the router to hang if ServiceBuilder::build() failed.
This commit makes sure the Telemetry plugin is cleanly shutdown when it's the case, thus correctly erroring out instead of hanging.

2022-04-13 18:14 UTC, garypen approved these changes

2022-04-13 19:59 UTC, BrynCooke commented on apollo-router/src/plugins/telemetry/mod.rs
> +        // This allows us to make sure the telemetry related globals
Gut feeling is that this will activate even if it was not supposed to, which would make this incorrect.
Let's talk this through.

2022-04-13 19:59 UTC, BrynCooke requested changes
I'm not confident about this, let's talk it through before merging.

2022-04-14 13:16 UTC, BrynCooke commented
Closing as #849 got merged

2022-04-14 13:16 UTC, closed without merging